/* Modelagem Básica -
 
ENTIDADE = TABLE
CAMPOS = ATRIBUTOS */

CLIENTE

USERNAME - CARACTER (20)
PASSWORD - CARACTER (8)
CPF - NUMERIC (11)
NAME - CARACTER(50)
EMAIL - CARACTER (30)
TELEFONE - CARACTER (13)
ENDERECO - CARACTER (100)
SEXO - CARACTER (1)

INSTRUTOR

MATRICULA - CARACTER (11)
NAME - CARACTER (30)
SALARIO - CARACTER (5)

MODALIDADE

NOME - CARACTER (20)
HORARIO - NUMERICO (5)

/* PROCESSO DE MODELAGEM */

/* FASE 01 E FASE 02 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO